# Ch01. 신경망 복습

## 1.1. 수학과 파이썬 복습

#### 벡터와 행렬 생성

In [1]:
import numpy as np

x = np.array([1, 2, 3])

In [2]:
# 클래스 이름 표시
x.__class__

numpy.ndarray

In [3]:
x.shape

(3,)

In [4]:
x.ndim

1

In [6]:
W = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
W.shape

(2, 3)

In [8]:
W.ndim

2

#### 행렬의 원소별 연산

In [9]:
W = np.array([[1,2,3],[4,5,6]])
X = np.array([[0,1,2],[3,4,5]])

In [10]:
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [11]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

#### 브로드캐스트(Broadcast)

넘파이의 다차원 배열에서는 형상이 다른 배열끼리도 연산할 수 있다.

In [12]:
A = np.array([[1,2],[3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [14]:
A = np.array([[1,2],[3,4]])
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

#### 벡터의 내적

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a, b)

32

#### 행렬의 곱

In [16]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
np.matmul(A, B)    # np.dot(A, B)

array([[19, 22],
       [43, 50]])

## 1.2. 신경망의 추론

#### TwoLayerNet의 구현

In [18]:
# coding: utf-8
import numpy as np


class Sigmoid:
    def __init__(self):
        self.params = []

    def forward(self, x):
        return 1 / (1 + np.exp(-x))


class Affine:
    def __init__(self, W, b):
        self.params = [W, b]

    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out


class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 가중치와 편향 초기화
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # 계층 생성
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 모든 가중치를 리스트에 모은다.
        self.params = []
        for layer in self.layers:
            self.params += layer.params

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x


x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(s)

[[ 0.64150306 -1.28566536 -3.06957188]
 [ 0.73232601 -1.26447365 -3.04356888]
 [ 0.95119429 -0.58505618 -2.61847467]
 [ 0.67018403 -1.29578995 -3.06845522]
 [ 0.44440218 -0.75704805 -3.06538385]
 [ 0.72656973 -1.24392683 -3.02660804]
 [ 0.74718548 -1.19750913 -2.99238785]
 [ 0.69708256 -1.14502679 -2.97717468]
 [ 1.05545781 -0.62765424 -2.59127873]
 [ 0.86471587 -0.91621558 -2.80058641]]
